name: flutter_falling_items
description: A Flutter package for falling item animations like flowers, coins, etc.
version: 0.2.0
publish_to: "none" # Prevents publishing to pub.dev

homepage: https://github.com/dhanushequinox/fallingitem
repository: https://github.com/dhanushequinox/fallingitem

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Screenshot_1745923899.png
